//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class castphotogallery
    {
        public int id { get; set; }
        public Nullable<int> castTableid { get; set; }
        public string castIpath { get; set; }
        public byte[] imageC { get; set; }
        public string castimagename { get; set; }
    
        public virtual Movie_Item Movie_Item { get; set; }
    }
}
