//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class castlike
    {
        public int likeid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> castid { get; set; }
        public Nullable<int> likecount { get; set; }
    
        public virtual movieCastcrew movieCastcrew { get; set; }
        public virtual usertbl usertbl { get; set; }
    }
}
