//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class castComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public castComment()
        {
            this.castreplies = new HashSet<castreply>();
        }
    
        public int ccid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> castrid { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> comdate { get; set; }
    
        public virtual castratingsT castratingsT { get; set; }
        public virtual usertbl usertbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<castreply> castreplies { get; set; }
        public virtual movieCastcrew movieCastcrew { get; set; }
    }
}
