//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chatmessage
    {
        public int chatid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> chattime { get; set; }
        public string username { get; set; }
        public string chatmessage1 { get; set; }
    
        public virtual usertbl usertbl { get; set; }
    }
}
