//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodOrderTbl
    {
        public int foodOrdId { get; set; }
        public Nullable<int> movieid { get; set; }
        public Nullable<int> foodInvoiceid { get; set; }
        public Nullable<int> hallid { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> bill { get; set; }
        public Nullable<double> unitprice { get; set; }
    
        public virtual halltable halltable { get; set; }
        public virtual nowshowing nowshowing { get; set; }
        public virtual foodInvoice foodInvoice { get; set; }
    }
}
