//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallFoodTbl
    {
        public int foodID { get; set; }
        public string foodName { get; set; }
        public string foodDiscription { get; set; }
        public string foodimage { get; set; }
        public Nullable<int> hallid { get; set; }
        public Nullable<double> Fprice { get; set; }
    
        public virtual halltable halltable { get; set; }
    }
}
