//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inovice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inovice()
        {
            this.ordertables = new HashSet<ordertable>();
        }
    
        public int invoiceid { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> userTblid { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> totalbill { get; set; }
    
        public virtual shoppingcart shoppingcart { get; set; }
        public virtual usertbl usertbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordertable> ordertables { get; set; }
    }
}
