//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class moviesdb : DbContext
    {
        public moviesdb()
            : base("name=moviesdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<movietbl1> movietbl1 { get; set; }
        public virtual DbSet<heroarenatable> heroarenatables { get; set; }
        public virtual DbSet<newsforum> newsforums { get; set; }
        public virtual DbSet<trailertb> trailertbs { get; set; }
    }
}
