//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movieshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movieshop()
        {
            this.Landmark121 = new HashSet<Landmark121>();
        }
    
        public int shopid { get; set; }
        public string shopname { get; set; }
        public string ownername { get; set; }
        public Nullable<System.DateTime> registredDate { get; set; }
        public Nullable<System.DateTime> establisheddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Landmark121> Landmark121 { get; set; }
    }
}
