//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie_Item()
        {
            this.PhotoGalleries = new HashSet<PhotoGallery>();
            this.shoppingcarts = new HashSet<shoppingcart>();
            this.castphotogalleries = new HashSet<castphotogallery>();
            this.ordertables = new HashSet<ordertable>();
            this.comments = new HashSet<comment>();
            this.movieCastcrews = new HashSet<movieCastcrew>();
            this.Review_Table = new HashSet<Review_Table>();
            this.Landmark121 = new HashSet<Landmark121>();
        }
    
        public int movie_id { get; set; }
        public string Movie_name { get; set; }
        public Nullable<System.DateTime> Movie_release { get; set; }
        public string Movie_director { get; set; }
        public string imgpath { get; set; }
        public byte[] imageCover { get; set; }
       // public Nullable<System.DateTime> Posted_date { get; set; }
        public string movieDis { get; set; }
        public string category { get; set; }
        public Nullable<bool> awardnominated { get; set; }
        public Nullable<bool> banned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoGallery> PhotoGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shoppingcart> shoppingcarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<castphotogallery> castphotogalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordertable> ordertables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movieCastcrew> movieCastcrews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review_Table> Review_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Landmark121> Landmark121 { get; set; }
    }
}
