//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordertable
    {
        public int orderid { get; set; }
        public Nullable<int> prodid { get; set; }
        public Nullable<int> invoiceid { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> bill { get; set; }
        public Nullable<int> unitprice { get; set; }
    
        public virtual inovice inovice { get; set; }
        public virtual Movie_Item Movie_Item { get; set; }
    }
}
