//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoGallery
    {
        public int photoID { get; set; }
        public Nullable<int> moviPhotoId { get; set; }
        public string ipath { get; set; }
        public byte[] binary { get; set; }
        public string movietitle { get; set; }
    
        public virtual Movie_Item Movie_Item { get; set; }
    }
}
