//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review_Table
    {
        public int review_id { get; set; }
        public string Content { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
        public Nullable<int> movieT_ID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<double> cast_ratings { get; set; }
        public Nullable<int> castC_id { get; set; }
    
        public virtual Movie_Item Movie_Item { get; set; }
        public virtual usertbl usertbl { get; set; }
        public virtual movieCastcrew movieCastcrew { get; set; }
    }
}
