//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoppingcart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shoppingcart()
        {
            this.inovices = new HashSet<inovice>();
        }
    
        public int shopid { get; set; }
        public Nullable<int> movieItemDis { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<bool> isavailable { get; set; }
        public Nullable<double> PreviousPrice { get; set; }
        public Nullable<int> quantityavail { get; set; }
        public string coverphotopath { get; set; }
       // public Nullable<System.DateTime> publishdate { get; set; }
    
        public virtual Movie_Item Movie_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inovice> inovices { get; set; }
    }
}
