//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickettbl
    {
        public int ticketid { get; set; }
        public Nullable<int> movieid { get; set; }
        public Nullable<int> hallid { get; set; }
        public Nullable<int> showid { get; set; }
        public Nullable<int> halllocationid { get; set; }
        public string seatnobooked { get; set; }
        public Nullable<int> seatsbooked { get; set; }
        public Nullable<int> ticketcount { get; set; }
        public Nullable<double> bookedprice { get; set; }
        public Nullable<int> userid { get; set; }
        public string registredname { get; set; }
    
        public virtual hallLocation hallLocation { get; set; }
        public virtual halltable halltable { get; set; }
        public virtual nowshowing nowshowing { get; set; }
        public virtual showtime showtime { get; set; }
        public virtual usertbl usertbl { get; set; }
    }
}
